language: android
android:
  components:
  - android-20
  - build-tools-20.0.0
  - build-tools-20
  - platform-tools-20
before_install:
- openssl aes-256-cbc -pass "pass:$KEYSTORE_ENC_PASSWORD" -in ./moin.jks.enc -out
  ./moin.jks -d -a
script:
  - ./gradlew build assembleRelease
env:
  global:
  - secure: otwhqmDayCUfUImn53jLzrywJfoJS0o30R4H7rDsnBiEmKK5sZFrY7NOc37EXxpgSrjuuRuoNNTWZzBpMtle5qUbpD0/2PtFGnl1aysfWll3MjhEK9SfmVY3woK+qUs6x/OkYnbxnrAAdRugOu12RFn8ScEkElDINY8vadTX3YU=
  - secure: N4d7AiUbjmUf7DTVzC4oYUd3akPgklVgwZUiAmAuWUD94BVNLouWmYaa7EybvpDtSQ+xR3JOq92AHquVMorOjVy89s9yPqvRYRAkadX5mgluQZ5X9haxHadcBy1JP/2IcOP01v6Oo2IEsQ9+jZFNOxD2rOCN/hiABJZ+KlE6Yr8=
