language: android
sudo: false
android:
  components:
  - android-21
  - build-tools-21.1.1
  - platform-tools-21
before_install:
- openssl aes-256-cbc -pass "pass:$KEYSTORE_ENC_PASSWORD" -in ./moin.jks.enc -out
  ./moin.jks -d -a
script:
- "./gradlew assembleRelease"
env:
  global:
  - secure: otwhqmDayCUfUImn53jLzrywJfoJS0o30R4H7rDsnBiEmKK5sZFrY7NOc37EXxpgSrjuuRuoNNTWZzBpMtle5qUbpD0/2PtFGnl1aysfWll3MjhEK9SfmVY3woK+qUs6x/OkYnbxnrAAdRugOu12RFn8ScEkElDINY8vadTX3YU=
  - secure: N4d7AiUbjmUf7DTVzC4oYUd3akPgklVgwZUiAmAuWUD94BVNLouWmYaa7EybvpDtSQ+xR3JOq92AHquVMorOjVy89s9yPqvRYRAkadX5mgluQZ5X9haxHadcBy1JP/2IcOP01v6Oo2IEsQ9+jZFNOxD2rOCN/hiABJZ+KlE6Yr8=
before_deploy:
- export VERSION_NAME=`git describe --tags`
- mv mobile/build/outputs/apk/mobile-release.apk ./Moin-$VERSION_NAME.apk
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Tqwh/Wc4Et1RCVSf4FxfvcoSaoSl2V4T62rwqur4E4UYy9wAXu0HslJ5dUP/NxfbtSxb9x/TisVcH6/a4N7o/L+vom23aBOFxXZYCEDtWX7LPWi0jKi8GyAWEAEp083xrf0ar8KLldylFGHTWnvLm/fexV6QrxfxzUB4GI6uB3k=
  file: ./Moin-$VERSION_NAME.apk
  on:
    repo: MoinApp/moinapp-android
    tags: true
    all_branches: true

