package de.moinapp.moin.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FRIEND.
 */
public class Friend {

    private Long id;
    private String uuid;
    private String username;
    private String email;
    private Integer moins;

    public Friend() {
    }

    public Friend(Long id) {
        this.id = id;
    }

    public Friend(Long id, String uuid, String username, String email, Integer moins) {
        this.id = id;
        this.uuid = uuid;
        this.username = username;
        this.email = email;
        this.moins = moins;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getMoins() {
        return moins;
    }

    public void setMoins(Integer moins) {
        this.moins = moins;
    }

}
